config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root "pages#home_page"

  resources :courses do
    resources :course_dates do
      member do
        get 'course_details'
      end
      resources :tickets do
        resources :entries
      end
    end
  end

  resources :tickets do
    resources :payments
  end

  resources :course_dates do
    resources :bookings
  end

  resources :payments

  resources :booking_dates

  resources :plans
  resources :subscriptions

  devise_for :users

  get 'users/course_providers', :to => 'users#course_providers_index'
  get 'users/:id/calendar', :to => 'users#calendar'

  resources :users, :only => [:show, :edit, :update, :index] do
  end

  resource :dashboard do
    get 'months_bookings_csv'
    get 'all_bookings_csv'
    get 'transactions'
    get 'weeks_transactions_csv'
    get 'weeks_bookings_csv'
    get 'months_transactions_csv'
    get 'all_transactions_csv'
    get 'bookings'
    get 'withdraw'
  end

  get '/about', :to => 'pages#about'
  get '/faq', :to => 'pages#faq'
  get '/sales_and_refunds', :to => 'pages#sales_and_refunds'
  get '/offer', :to => 'pages#offer'
  get '/home', :to => 'pages#home_page'
  get '/how_it_works', :to => 'pages#how_it_works'
  get '/examples', :to => 'pages#examples'

end

app/views/templates/_footer.html.erb
<div class="ui inverted footer vertical segment" style="background-color: #36464f !important; margin-top:20px;">
  <div class="container">
    <div class="ui stackable inverted divided relaxed grid">
      <div class="eight wide column">
      	<h2 class="ui inverted header">About</h2>
      	<p>At Courseiam, we make it really easy for people to find and book their chosen course, using our integrated booking and administration system for Course Providers.</p>
      	<div class="ui inverted divided link horizontal list">
				  <%= link_to "About", about_path, :class => "item"  %>
				  <%= link_to "FAQ", faq_path, :class => "item"  %>
				</div>
      </div>
      <div class="four wide column">
        <h5 class="ui teal inverted header"></h5>
        <div class="ui inverted link list">
          <%= link_to "About", about_path, :class => "item"  %>
          <%# link_to "Offer", offer_path, :class => "item"  %>
          <%= link_to "FAQ", faq_path, :class => "item"  %>
          <%= link_to "How it Works", how_it_works_path, :class => "item"  %>
        </div>
      </div>
      <div class="four wide column">
        <h5 class="ui teal inverted header"></h5>
        <div class="ui inverted link list">
          <a class="item">Facebook</a>
          <a class="item">Twitter</a>
          <a class="item">Instagram</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/templates/_mobile_header.html.erb
<div class="ui top attached demo menu mobile">
  <a class="open_item item burger">
    <i class="sidebar icon"></i>
  </a>
</div>

app/views/templates/_quick_links.html.erb
<div class="ui segment" style="padding-top: 1em">
	<div class="ui red label quick-links">
	  <i class="bookmark icon"></i> Quick Links
	</div>
	<div class="ui list">
		<div class="item">
			<%= link_to "<i class='right triangle icon'></i>Create New Course".html_safe, new_course_path %>
		</div>
		<div class="item">
			<%= link_to "<i class='right triangle icon'></i>My Bookings".html_safe, about_path %>
		</div>
		<div class="item">
			<a id="monthlySummaryButton"><i class='right triangle icon'></i>Monthly Overview</a>
		</div>
		<div class="item">
			<%= link_to "<i class='right triangle icon'></i>Edit Details".html_safe, edit_user_path(@user.id) %>
		</div>
	</div>
</div>

app/views/templates/_web_header.html.erb
<div class="ui menu">
  <%= link_to( image_tag( "Courseiam2-blue.png" ), root_url, :class => "logo header item") %>
  <%= link_to("Discover", course_dates_path, :class => "item") %>
  <%= link_to("How it works", how_it_works_path, :class => "item") %>
  <div class="right menu">

    <div class="ui pointing dropdown link item">
      <span class="text"><i class="settings icon"></i>settings</span>
      <div class="menu">
        <%= link_to "About us", about_path ,:class => "item" %>
        <%= link_to "FAQ's", faq_path ,:class => "item" %>
        <% if signed_in? %>
          <% if current_user.admin? || nil %>
            <%= link_to("Edit Details", edit_user_path(current_user.id), :class => "item") %>
            <%= link_to("Log out".html_safe, destroy_user_session_path, :method => :delete, :class => "item") %>
          <% end %>
        <% end %>
      </div>
    </div>

    <% if signed_in? %>

      <% if current_user.admin? || nil%>
        <%= link_to("<i class='add square icon'></i>Add Course".html_safe, new_course_path, :class => "item" ,:id => "addCourse", :style => "  background-color:#36464f; color:white;") %>
        <%= link_to( "Dashboard".html_safe, dashboard_path, :class => "item" ) %>
      <% else %>
        <%= link_to("Log out".html_safe, destroy_user_session_path, :method => :delete, :class => "item") %>
      <% end %>

    <% else %>

      <a class="item" id="signIn" href="#">
        <i class="user icon"></i>
        Sign in
      </a>
      <%= link_to("<i class='sign in icon'></i>Sign up".html_safe, new_user_registration_path, :class => "item", :id => "signUp") %>

    <% end %>
  </div>
</div>