config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root "pages#home_page"

  resources :courses do
    resources :course_dates do
      member do
        get 'course_details'
      end
      resources :tickets do
        resources :entries
      end
    end
  end

  resources :tickets do
    resources :payments
  end

  resources :course_dates do
    resources :bookings
  end

  resources :payments

  resources :booking_dates

  resources :plans
  resources :subscriptions

  devise_for :users

  get 'users/course_providers', :to => 'users#course_providers_index'
  get 'users/:id/calendar', :to => 'users#calendar'

  resources :users, :only => [:show, :edit, :update, :index] do
  end

  resource :dashboard do
    get 'months_bookings_csv'
    get 'all_bookings_csv'
    get 'transactions'
    get 'weeks_transactions_csv'
    get 'weeks_bookings_csv'
    get 'months_transactions_csv'
    get 'all_transactions_csv'
    get 'bookings'
    get 'withdraw'
  end

  get '/about', :to => 'pages#about'
  get '/faq', :to => 'pages#faq'
  get '/sales_and_refunds', :to => 'pages#sales_and_refunds'
  get '/offer', :to => 'pages#offer'
  get '/home', :to => 'pages#home_page'
  get '/how_it_works', :to => 'pages#how_it_works'
  get '/examples', :to => 'pages#examples'

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	before_action :fetch_and_authorize_user

	def show
		@all_courses = @user.courses
		@active_courses = @all_courses.all.includes(:course_dates)
		@course_dates = []
		@active_courses.each do |course|
			course.course_dates.each do |date|
				if date.start_date_time > DateTime.now
					@course_dates << date
				end
			end
		end
    @all_dates =  CourseDate.all.select {|n| n.course.user.id == @user.id}
		@course_dates.sort_by!{|date| date.start_date_time}
		@company_payments = Payment.all.select{|payment| payment.company_id == @user.id }
    @undeposited_payments = @company_payments.select {|payment| payment.deposited == false}
		if @undeposited_payments.count > 0
			@price = @undeposited_payments.map do |p|
				if p.manually_added == false
          p.amount_paid
        end
			end
			@revenue = @price.compact.inject {|sum, n| sum += n }
		else
			@revenue = 0
			@monthly_payments = []
		end
	end

	def transactions
		@payments = Payment.all.select{|payment| payment.company_id == @user.id }
    @payments = @payments.compact
    @payments.sort_by! do |payment|
      payment.created_at
    end
    @payments = @payments.reverse
		@weekly_payments = @payments.select {|n| n.created_at >= DateTime.now.beginning_of_week}
		@monthly_payments = @payments.select {|n| n.created_at >= DateTime.now.beginning_of_month}
	end

	def weeks_transactions_csv
		csv_string = CSV.generate do |csv|
      csv << ['Name', 'Ammount paid', 'Fees', 'Net', 'Transaction date' ]
      @payments = Payment.all.select{|payment| payment.company_id == @user.id }
      @weekly_payments = @payments.select {|n| n.created_at >= DateTime.now.beginning_of_week}
      @payments = @weekly_payments.map do |payment|
      	payment
      end
      @payments.each do |payment|
        client_data = []
        client_data << payment.bookings.last.name
        client_data << payment.amount_paid.to_s
        client_data << payment.ticket_fee
        client_data << payment.profit
        client_data << payment.created_at.strftime("%A, %d %b %Y %l:%M %p")
        csv << client_data
      end
    end
    respond_to do |format|
      format.csv do
        response.headers['Content-Type'] = 'text/csv'
        response.headers['Content-Disposition'] = 'attachment; filename=transactions.csv'
        render text: csv_string
      end
    end
	end

	def months_transactions_csv
		csv_string = CSV.generate do |csv|
      csv << ['Name', 'Ammount paid', 'Fees', 'Net', 'Transaction date' ]
      @payments = Payment.all.select{|payment| payment.company_id == @user.id }
      @monthly_payments = @payments.select {|n| n.created_at >= DateTime.now.beginning_of_month}
      @payments = @monthly_payments.map do |payment|
      	payment
      end
      @payments.each do |payment|
        client_data = []
        client_data << payment.bookings.last.name
        client_data << payment.amount_paid.to_s
        client_data << payment.ticket_fee
        client_data << payment.profit
        client_data << payment.created_at.strftime("%A, %d %b %Y %l:%M %p")
        csv << client_data
      end
    end
    respond_to do |format|
      format.csv do
        response.headers['Content-Type'] = 'text/csv'
        response.headers['Content-Disposition'] = 'attachment; filename=transactions.csv'
        render text: csv_string
      end
    end
	end

	def all_transactions_csv
		csv_string = CSV.generate do |csv|
      csv << ['Name', 'Ammount paid', 'Fees', 'Net', 'Transaction date' ]
      @payments = Payment.all.select{|payment| payment.company_id == @user.id }
      @payments = @payments.map do |payment|
      	payment
      end
      @payments.each do |payment|
        client_data = []
        client_data << payment.bookings.last.name
        client_data << payment.amount_paid.to_s
        client_data << payment.ticket_fee
        client_data << payment.profit
        client_data << payment.created_at.strftime("%A, %d %b %Y %l:%M %p")
        csv << client_data
      end
    end
    respond_to do |format|
      format.csv do
        response.headers['Content-Type'] = 'text/csv'
        response.headers['Content-Disposition'] = 'attachment; filename=transactions.csv'
        render text: csv_string
      end
    end
	end

	def bookings
    @booking_dates = BookingDate.all.select{|date| date.course_date.course.user.id == @user.id }
    @booking_dates.compact
		@weekly_bookings = @booking_dates.select {|n| n.created_at >= DateTime.now.beginning_of_week}
    @monthly_bookings = @booking_dates.select {|n| n.created_at >= DateTime.now.beginning_of_month}
	end

  def weeks_bookings_csv
    csv_string = CSV.generate do |csv|
      csv << ['Course', 'Start date', 'Name', 'Email', 'Contact number',  'Created at']
      @booking_dates = BookingDate.all.select{|date| date.course_date.course.user.id == @user.id }
      @weekly_bookings = @booking_dates.select {|n| n.created_at >= DateTime.now.beginning_of_week}
      @booking_dates = @weekly_bookings.map do |booking|
        booking
      end
      @booking_dates.each do |date|
        client_data = []
        client_data << date.course_date.course.name
        client_data << date.course_date.start_date.strftime("%d/%m/%Y")
        client_data << date.booking.name
        client_data << date.booking.email
        client_data << date.booking.contact_number
        client_data << date.booking.created_at.strftime("%A, %d %b %Y %l:%M %p")
        csv << client_data
      end
    end
    respond_to do |format|
      format.csv do
        response.headers['Content-Type'] = 'text/csv'
        response.headers['Content-Disposition'] = 'attachment; filename=WeeksBookings.csv'
        render text: csv_string
      end
    end
  end

  def months_bookings_csv
    csv_string = CSV.generate do |csv|
      csv << ['Course', 'Start date', 'Name', 'Email', 'Contact number',  'Created at']
      @booking_dates = BookingDate.all.select{|date| date.course_date.course.user.id == @user.id }
      @monthly_bookings = @booking_dates.select {|n| n.created_at >= DateTime.now.beginning_of_month}
      @booking_dates = @monthly_bookings.map do |booking|
        booking
      end
      @booking_dates.each do |date|
        client_data = []
        client_data << date.course_date.course.name
        client_data << date.course_date.start_date.strftime("%d/%m/%Y")
        client_data << date.booking.name
        client_data << date.booking.email
        client_data << date.booking.contact_number
        client_data << date.booking.created_at.strftime("%A, %d %b %Y %l:%M %p")
        csv << client_data
      end
    end
    respond_to do |format|
      format.csv do
        response.headers['Content-Type'] = 'text/csv'
        response.headers['Content-Disposition'] = 'attachment; filename=WeeksBookings.csv'
        render text: csv_string
      end
    end
  end

  def all_bookings_csv
    csv_string = CSV.generate do |csv|
      csv << ['Course', 'Start date', 'Name', 'Email', 'Contact number',  'Created at']
      @all_bookings = BookingDate.all.select{|date| date.course_date.course.user.id == @user.id }
      @booking_dates = @all_bookings.map do |booking|
        booking
      end
      @booking_dates.each do |date|
        client_data = []
        client_data << date.course_date.course.name
        client_data << date.course_date.start_date.strftime("%d/%m/%Y")
        client_data << date.booking.name
        client_data << date.booking.email
        client_data << date.booking.contact_number
        client_data << date.booking.created_at.strftime("%A, %d %b %Y %l:%M %p")
        csv << client_data
      end
    end
    respond_to do |format|
      format.csv do
        response.headers['Content-Type'] = 'text/csv'
        response.headers['Content-Disposition'] = 'attachment; filename=WeeksBookings.csv'
        render text: csv_string
      end
    end
  end

  def withdraw
    @company_payments = Payment.all.select{|booking| booking.company_id == @user.id }
    @undeposited_payments = @company_payments.select {|payment| payment.deposited == false}
    DashboardMailer.withdraw_payments(@user).deliver!
    DashboardMailer.withdraw_notification(@user).deliver!
    @undeposited_payments.each do |payment|
      payment.update_attributes(:deposited => true)
    end
    @user.update_attributes(:fees => 0.00)
    flash[:notice] = 'Successfully requested withdraw of funds'
    redirect_to dashboard_path
  end

	private

  def fetch_and_authorize_user
    if current_user.nil?
      raise 'Unauthorized'
    elsif current_user.admin != true
      raise 'Unauthorized'
    else
      @user = current_user
    end
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboards/_active_course_list.html.erb
<div class="ui divided list course-list">
	<% @courses.each do |course|%>
	  <div class="item">
	  	<%= image_tag course.avatar_url(:medium) ,:class => "course-image" %>
	    <div class="content">
	      <a class="header"><%= course.name %></a>
	    	<div class="ui link list">
	    		<% course.upcoming_dates.each do |course_date| %>
				  	<a class="item date-link course"><i class='calendar icon'></i><%= course_date.start_date.strftime("%d/%m/%Y")%> (<%= course_date.payments.count%>/<%= course_date.quantity %>)</a>
				  	<div class="ui popup right">
						  <div class="header">view course date info</div>
						</div>
				  	<div class="ui modal allCourses">
						  <i class="close icon"></i>
						  <div class="header">
						    <%= course.name %>
						  </div>
						  <div class="content">
						  	<%= course_date.start_date.strftime("%d/%m/%Y")%>
						    <table class="ui celled striped table">
						      <thead>
						        <tr>
						          <th class="two wide">Order No.</th>
						          <th class="four wide">Name</th>
						          <th class="four wide">Email</th>
						          <th class="three wide">Mobile</th>
						          <th class="four wide">Special Requests</th>
						        </tr>
						      </thead>
						      <tbody>
						        <% course_date.payments.each do |payment| %>
						          <tr>
						            <td><%= payment.id %></td>
						            <td><%= payment.full_name %></td>
						            <td><%= payment.email %></td>
						            <td><%= payment.mobile_number %></td>
						            <td></td>
						          </tr>
						        <% end %>
						      </tbody>
						    </table>
						  	<div class="ui teal progress" id="example2" data-attibute="<%= @course_date %>" style="margin-top:10px;">
					        <div class="bar"></div>
					        <div class="label"><%= course_date.sale_percentage %>% Full</div>
					      </div>
						  </div>
						</div>
				  <% end %>
				</div>
	    </div>
      <div class="actions">
      	<div class="ui basic buttons">
				  <div class="ui button"><%= link_to("<i class='edit icon'></i>".html_safe ,edit_course_path(course.id))%>
				  </div>
					<div class="ui popup">
					  <div class="header">Edit course</div>
					</div>

				  <div class="ui button"><%= link_to("<i class='calendar icon'></i>".html_safe, new_course_course_date_path(course.id)) %>
				  </div>
				  <div class="ui popup">
					  <div class="header">Add course date</div>
					</div>
				</div>
      </div>
	  </div>
  <% end %>
</div>

app/views/dashboards/_admin_board.html.erb
<%= render "monthly_summary_modal" %>
<div class="ui segment admin-board">
	<div class="two column stackable ui grid">
		<div class="column three wide">
			<%= render "templates/quick_links" %>
		</div>
		<div class="column thirteen wide">
			<div class="ui top attached tabular menu">
		    <a class="active item" data-tab="first">Active Courses (<%= @courses.count %>) </a>
		    <a class="item" data-tab="second">All Courses (<%= @all_courses.count %>) </a>
		    <!-- <a class="item" data-tab="third">Unactive Courses (1) </a> -->
		  </div>
			<div class="ui bottom attached active tab segment" data-tab="first">
			  <%= render "active_course_list" %>
			</div>
			<div class="ui bottom attached tab segment" data-tab="second">
				<%= render "all_course_list" %>
			</div>
		</div>
	<!-- <div class="ui bottom attached tab segment" data-tab="third">
	  Third
	</div> -->
	</div>
</div>

app/views/dashboards/_all_courses_modal.html.erb
<div class="ui modal" id="allCourses">
  <i class="close icon"></i>
  <div class="header">
    All my Courses
  </div>
  <div class="content">

    <table class="ui celled striped table">
      <thead>
        <tr>
          <th class="five wide">Course Name</th>
          <th class="three wide">Dates Created</th>
          <th class="three wide">Active Dates</th>
          <th class="three wide">Payments Taken</th>
          <th class="one wide">Edit Course</th>
          <th class="one wide">Add Course Date</th>
        </tr>
      </thead>
      <tbody>
        <% @all_courses.each do |course| %>
          <tr>
            <td ><%= course.name.truncate(30) %></td>
            <td ><%= course.course_dates.count %></td>
            <td ><%=course.upcoming_dates.count%></td>
            <td ><%= course.course_dates(&:payments?).count %></td>
            <td ><%= link_to("<i class='edit icon' style='margin:auto; display:block'></i>".html_safe ,edit_course_path(course.id))%></td>
            <td ><%= link_to("<i class='add icon' style='margin:auto; display:block'></i>".html_safe, new_course_course_date_path(course.id)) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>

  <div class="actions">
    <div class="ui black button">
      Nope
    </div>
    <button type='submit' form='ticket_form' class="ui positive right labeled icon button">
      Create a new course
      <i class="checkmark icon"></i>
    </button>
  </div>
</div>

app/views/dashboards/_all_transactions.html.erb
<%= link_to 'Download <i class="download icon"></i>'.html_safe, all_transactions_csv_dashboard_path(format: :csv), :class => "ui button " %>
<table class="ui celled table">
  <thead>
    <tr>
      <th>Transaction Date</th>
      <th>Name</th>
      <th>Paid</th>
      <th>Fee</th>
      <th>Net Profit</th>
    </tr>
  </thead>
  <tbody>
	  <% @payments.each do |payment| %>
	    <tr>
        <td><%= time_ago_in_words(payment.created_at)%> ago</td>
        <td><%= payment.bookings.last.name %></td>
        <% if payment.amount_paid.to_s == "0.0" %>
          <td><%= number_to_currency(payment.ticket.price, :precision => 2, :unit => "£") %></td>
        <% else %>
          <td><%= number_to_currency(payment.amount_paid, :precision => 2, :unit => "£") %></td>
        <% end %>
        <% if payment.ticket_fee.to_s == "0.0" %>
          <td><%= number_to_currency((payment.ticket.price * 0.04), :precision => 2, :unit => "£") %></td>
        <% else %>
          <td><%= number_to_currency(payment.ticket_fee, :precision => 2, :unit => "£") %></td>
        <% end %>
        <td><%= number_to_currency(payment.profit, :precision => 2, :unit => "£") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/dashboards/_course_list.html.erb
<h1 class="header" style="margin-bottom: 35px;">Course List</h1>
<table class="ui very basic table course-list-table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Course Dates Created</th>
      <th>Active Course Dates</th>
      <th style="text-align: center">Actions</th>
    </tr>
  </thead>
  <tbody>
  	<% @all_courses.each do |course|%>
		    <tr>
		      <td><%= link_to(course.name, course_path(course)) %></td>
          <%# link_to(course_date.course.name, course_path(course_date.course), :class => "header text", :style => "color: white; font-size: 1em;") %>
		      <td><%= course.course_dates.count %></td>
		      <td><%= course.upcoming_dates.count %></td>
		      <td style="text-align:center"><%= link_to("Add Date".html_safe, new_course_course_date_path(course.id), :class =>"ui inverted red button", :id => 'addDate')%>
          <br>
            <%= link_to("Edit Text", edit_course_path(course.id), :class =>"ui inverted green button", :style => "margin-top:10px;") %>
		      </td>
		    </tr>
	   <% end %>
  </tbody>
</table>

app/views/dashboards/_monthly_summary_modal.html.erb
<div class="ui small modal" id="monthlySummary">
  <i class="close icon"></i>
  <a class="ui blue label" style="margin-bottom:20px; margin-left: 0px;">
    <h4 class="ui header" style="color:white">ABOUT THIS COURSE</h4>
  </a>
  <div class="content">
    <table class="ui definition table">
      <tbody>
        <tr>
          <td class="ten wide column">Bookings</td>
          <td><%= @monthly_payments.count %></td>
        </tr>
        <tr>
          <td>Revenue</td>
          <% if @payments.blank? %>
              <td>None so far</td>
          <% else %>
              <td>£<%= @revenue %></td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/dashboards/_months_bookings.html.erb
<%= link_to 'Download <i class="download icon"></i>'.html_safe, months_bookings_csv_dashboard_path(format: :csv), :class => "ui button " %>
<table class="ui celled table">
  <thead>
    <tr>
      <th>Event</th>
      <th>Name</th>
      <th>Contact</th>
    </tr>
  </thead>
  <tbody>
	  <% @monthly_bookings.each do |date| %>
	    <tr>
        <td><%= date.course_date.course.name %><br/> <%= date.course_date.start_date.strftime("%A, %d %b") %></td>
        <td><%= date.booking.name %></td>
        <td><%= date.booking.email %><br/><%= date.booking.contact_number %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/dashboards/_previous_dates.html.erb
<h1 class="header" style="margin-bottom: 35px;">Previous Dates</h1>
<table class="ui very basic table previous-dates-table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Sold</th>
      <th style="text-align:center">Actions</th>
    </tr>
  </thead>
  <tbody>
  	<% @all_courses.each do |course|%>
  		<% course.previous_dates.each do |course_date| %>
		    <tr>
		      <td><%= course.name %></td>
		      <td><%= course_date.select_date%></td>
		      <% if course_date.full%>
            <td>Sold Out</td>
          <% else %>
            <td><%= course_date.tickets_left %></td>
          <% end %>
		      <td style="text-align:center"><%= link_to("Manage".html_safe, course_details_course_course_date_path(course_date.course_id, course_date.id), :class =>"ui inverted red button")%>
		      </td>
		    </tr>
	    <% end %>
	   <% end %>
  </tbody>
</table>

app/views/dashboards/_user_board.html.erb
hello

app/views/dashboards/_weeks_bookings.html.erb
<%= link_to 'Download <i class="download icon"></i>'.html_safe, weeks_bookings_csv_dashboard_path(format: :csv), :class => "ui button " %>
<table class="ui celled table">
  <thead>
    <tr>
      <th>Event</th>
      <th>Name</th>
      <th>Contact</th>
    </tr>
  </thead>
  <tbody>
	  <% @weekly_bookings.each do |date| %>
	    <tr>
        <td><%= date.course_date.course.name %><br/> <%= date.course_date.start_date.strftime("%A, %d %b") %></td>
        <td><%= date.booking.name %></td>
        <td><%= date.booking.email %><br/><%= date.booking.contact_number %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/dashboards/old-show.html.erb
<% if current_user.admin? %>
	<%= render 'admin_board' %>
<% else %>
	<%= render 'user_board' %>
<% end %>

app/views/dashboards/old_admin_board.html.erb
<%= render "all_courses_modal" %>
<div class="two column stackable ui grid" style="margin:0px;">
    <div class="column sixteen wide">
        <div class="ui segment" style="padding:1rem; display:block">
            <h1 style="margin:0px; display:inline-block"><%= @user.company_name %></h1>
            <%= link_to('Edit Company Details', edit_user_path(@user.id), :class => "ui inverted green button", :style => "float:right; width:250px; display:inline-block;") %>
        </div>
    </div>
    <!-- LEFT SIDE -->
    <div class="column five wide">
        <div class="ui segment">
            <div class="column">
                <% if @user.avatar_url.blank? %>
                    <div class="image" style="text-align:center; width:100%;">
                        <%= image_tag "placeholder.png", :style =>"width:100%;"%>
                    </div>
                <% else %>
                    <div class="image" style="text-align:center">
                        <%= image_tag(@user.avatar_url(:medium), :class => "ui medium rounded" )%>
                    </div>
                <% end %>
            </div>
            <div class="ui three column grid">
                <!-- <div class="column" style="text-align:center; padding-right:0; padding-left:0">
                    <p>256</p>
                    <p>HOURS TAUGHT </p>
                </div>
                <div class="column" style="text-align:center; padding-right:0; padding-left:0">
                    <p>256</p>
                    <p>HOURS TAUGHT </p>
                </div>
                <div class="column" style="text-align:center; padding-right:0; padding-left:0">
                    <p>256</p>
                    <p>HOURS TAUGHT </p>
                </div> -->
              </div>
        </div>
    </div>
    <!-- END OF LEFT SIDE -->
    <!-- RIGHT SIDE -->
    <div class="column eleven wide">
        <div class="ui segment">
            <!-- START OF THE TABLE -->
            <h3 style="margin:0px;">Upcoming Course Dates</h3>
            <table class="ui striped table" style="min-height: 210px;">
                <thead style="display:block">
                    <tr>
                        <th class="one wide">
                            #
                        </th>
                        <th class="seven wide">
                            Course Title
                        </th>
                        <th class="two wide center aligned">
                            Date
                        </th>
                        <th class="two wide center aligned">
                            Subscribers
                        </th>
                        <th class="three wide center aligned">
                            Max Revenue
                        </th>
                        <th class="one wide center aligned">
                            View
                        </th>
                    </tr>
                </thead>
                <tbody style="display: block; max-height: 208px; overflow-y: auto">
                    <% @courses.each do |course|%>
                        <% course.upcoming_dates.each do |course_date| %>
                        <tr style="display:block">
                            <td class="one wide collapsing">1</td>
                            <td class="seven wide"><%= course_date.course.name %></td>
                            <td class="two wide left aligned"><%= course_date.start_date.strftime("%d/%m/%Y")%></td>
                            <td class="two wide center aligned"><%= course_date.payments.count %>/<%= course_date.quantity%></td>
                            <td class="three wide center aligned"><%= course_date.max_revenue %></td>
                            <td class="one wide center aligned"><%= link_to("<i class='bar chart icon'></i>".html_safe, course_details_course_course_date_path(course_date.course_id, course_date.id))%></td>
                        </tr>
                        <% end %>
                    <% end %>
                </tbody>
            </table>
            <!-- END OF THE TABLE -->
            <div class="ui segment">
                <div class="ui three column stackable grid">
                    <div class="column">
                        <a><div id="course" class="ui button" style="display:block">SEE ALL COURSES</div></a>
                    </div>
                    <div class="column">
                        <a><div id="course" class="ui button" style="display:block"><%= link_to('NEW COURSE', new_course_path) %></div></a>
                    </div>
                    <div class="column">
                        <a><div id="course" class="ui button" style="display:block">NEW DATE</div></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END OF RIGHT SIDE -->
    <div class="column five wide">
        <div class="ui raised segment">
            <a class="ui red ribbon label">Monthly Summary</a>
            <table class="ui definition table">
                <tbody>
                    <tr>
                        <td class="ten wide column">Bookings</td>
                        <td><%= @payments.count %></td>
                    </tr>
                    <tr>
                        <td>Revenue</td>
                        <% if @payments.blank? %>
                            <td>None so far</td>
                        <% else %>
                            <td>£<%= @revenue %></td>
                        <% end %>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="column eleven wide">
        <div class="ui segment">
            <!-- AT THE MOMENT THIS GRAPH SHOWS YOU THE NUMBER OF COURSES CREATED FROM THE BEGINNING OF THE MONTH -->
                <%# line_chart @active_courses.group_by_day(:created_at, range: Date.today.beginning_of_month..Time.now).count %>
            <!-- END OF THE GRAPH -->

        </div>
    </div>
</div>

app/views/dashboards/old_all_courses_modal.html.erb
<div class="ui modal" id="allCourses">
  <i class="close icon"></i>
  <div class="header">
    All my Courses
  </div>
  <div class="content">

    <table class="ui celled striped table">
      <thead>
        <tr>
          <th class="five wide">Course Name</th>
          <th class="three wide">Dates Created</th>
          <th class="three wide">Active Dates</th>
          <th class="three wide">Payments Taken</th>
          <th class="one wide">Edit Course</th>
          <th class="one wide">Add Course Date</th>
        </tr>
      </thead>
      <tbody>
        <% @all_courses.each do |course| %>
          <tr>
            <td ><%= course.name.truncate(30) %></td>
            <td ><%= course.course_dates.count %></td>
            <td ><%=course.upcoming_dates.count%></td>
            <td ><%= course.course_dates(&:payments?).count %></td>
            <td ><%= link_to("<i class='edit icon' style='margin:auto; display:block'></i>".html_safe ,edit_course_path(course.id))%></td>
            <td ><%= link_to("<i class='add icon' style='margin:auto; display:block'></i>".html_safe, new_course_course_date_path(course.id)) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>

  <div class="actions">
    <div class="ui black button">
      Nope
    </div>
    <button type='submit' form='ticket_form' class="ui positive right labeled icon button">
      Create a new course
      <i class="checkmark icon"></i>
    </button>
  </div>
</div>

app/views/dashboards/transactions.html.erb
<div class="two column stackable ui grid dashboard" style="height:100%; background-color: #36464f;">
	<div class="column four wide" style="height: 100%">
		<div class="dash-sidenav">
			<div class="account">
		    <div class=""><%= image_tag @user.avatar_url(:thumb), :class => "profile-pic"%></div>
		    <div class="username"><%= @user.company_name %></div>
		  </div>
		  <div class="ui divider"></div>
			<!-- <div class="ui divider"></div> -->

			<div class="ui list side-buttons" style="text-align:center">
			  <%# link_to("Transactions", transactions_dashboard_path, :class => "item", :style => "text-align:center; color:white;") %>
				<%# link_to("Bookings", bookings_dashboard_path, :class => "item", :style => "text-align:center; color:white;") %>
				<%= link_to("Edit Company Details", edit_user_path(@user.id), :class => "item", :style => "text-align:center; color:white;") %>
			  <%= link_to( "Back to Dashboard".html_safe, dashboard_path, :class => "item" ) %>
			</div>
		</div>
	</div>
	<div class="column twelve wide" style="height: 100%; background:white; min-height:500px;">
		<div class="row" style="padding-bottom:30px;">
			<h1 class="header">Company Transactions</h1>
			<h3 class="header sub-heading">Check all your company transactions</h3>
		</div>
		<div class="ui pointing secondary menu">
	    <a class="active item" data-tab="first" style="width:33.3%; text-align:center;font-size: 18px;">Transactions this week<span style="display:block; font-size:16px; font-weight:100; margin-top:8px;">(<%= DateTime.now.beginning_of_week.strftime("%A, %d %b") %>)</span></a>
	    <a class="item" data-tab="second" style="width:33.3%; text-align:center;font-size: 18px;">Transactions this month<span style="display:block; font-size:16px; font-weight:100; margin-top:8px;">(<%= DateTime.now.beginning_of_month.strftime("%A, %d %b") %>)</span></a>
	    <a class="item" data-tab="third" style="width:33.3%; text-align:center;font-size: 18px;">All Transactions</a>
	  </div>
	  <div class="ui active tab" data-tab="first">
	  	<%= render "last_weeks_transactions" %>
		</div>
		<div class="ui tab" data-tab="second">
			<%= render "last_months_transactions" %>
		</div>
		<div class="ui tab" data-tab="third">
	  	<%= render "all_transactions" %>
		</div>
	</div>
</div>