config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root "pages#home_page"

  resources :courses do
    resources :course_dates do
      member do
        get 'course_details'
      end
      resources :tickets do
        resources :entries
      end
    end
  end

  resources :tickets do
    resources :payments
  end

  resources :course_dates do
    resources :bookings
  end

  resources :payments

  resources :booking_dates

  resources :plans
  resources :subscriptions

  devise_for :users

  get 'users/course_providers', :to => 'users#course_providers_index'
  get 'users/:id/calendar', :to => 'users#calendar'

  resources :users, :only => [:show, :edit, :update, :index] do
  end

  resource :dashboard do
    get 'months_bookings_csv'
    get 'all_bookings_csv'
    get 'transactions'
    get 'weeks_transactions_csv'
    get 'weeks_bookings_csv'
    get 'months_transactions_csv'
    get 'all_transactions_csv'
    get 'bookings'
    get 'withdraw'
  end

  get '/about', :to => 'pages#about'
  get '/faq', :to => 'pages#faq'
  get '/sales_and_refunds', :to => 'pages#sales_and_refunds'
  get '/offer', :to => 'pages#offer'
  get '/home', :to => 'pages#home_page'
  get '/how_it_works', :to => 'pages#how_it_works'
  get '/examples', :to => 'pages#examples'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	before_action :fetch_and_authorize_course, :except => [:index, :show]
	before_action :fetch_and_authorize_user, :except => [:index, :show, :new, :create]

	def new
		@course = Course.new
		@course.user = current_user
		@course.course_addresses.build
		course_dates = @course.course_dates.build
		course_dates.tickets.build
		@course.confirmation_emails.build
	end

	def create
		@course = Course.new(course_params)
		@course.user = current_user
		if @course.save
			@user =  @course.user
			render :crop
	  else
		  format.html { render action: 'new' }
		end
	end

	def index
		@active_courses = Course.all.includes(:course_dates).select do |course|
			course.course_dates.any?(&:active?)
		end
		@courses = @active_courses.sort_by! do |course|
			course.upcoming_date.start_date_time
		end
	end

	def show
	  @course = Course.find(params[:id])
	  @user = @course.user
	  render layout: "iframe-#{params[:embed]}" if params[:embed]
	end

	def edit
		@course = Course.find(params[:id])
	end

	def update
		@course = Course.find(params[:id])
		if @course.update_attributes(params[:course].permit(:name, :description, :price, :avatar, :crop_x, :crop_y, :crop_w, :crop_h, :what_to_wear, :what_to_bring, :experience, :category, confirmation_emails_attributes:[:content, :course_id, :id, :attachment_one, :attachment_two, :attachment_three], course_addresses_attributes:[:id, :postcode, :address1, :address2, :city, :county, :longitude, :latitude], course_dates_attributes:[:id, :start_time, :end_time, :start_date, :end_date, :absorb_fee, :number_of_dates]))
			if params[:course][:avatar].present?
				render :crop
			else
				redirect_to dashboard_path
				flash[:notice] = 'New Course Successfully Created'
			end
		else
			render :new
		end
	end

	private

	def fetch_and_authorize_course
		if current_user.nil?
			raise 'Unauthorized'
		else
			raise 'Unauthorized' unless current_user.admin == true
		end
	end

	def fetch_and_authorize_user
		@course = Course.find(params[:id])
		raise 'Unauthorized' unless @course.user == current_user
	end

	def course_params
    params.require(:course).permit(:name, :description, :price, :avatar, :crop_x, :crop_y, :crop_w, :crop_h, :what_to_wear, :private, :what_to_bring, :experience, :category, :age_needed, confirmation_emails_attributes:[:content, :course_id, :id, :attachment_one, :attachment_two, :attachment_three], course_addresses_attributes:[:id, :postcode, :address1, :address2, :city, :county, :longitude, :latitude], course_dates_attributes:[:id, :start_time, :end_time, :start_date, :end_date, :course_id, tickets_attributes:[:id, :name, :course_date_id, :price, :quantity, :absorb_fee, :number_of_dates]])
	end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_book_date.html.erb
<div class="ui small modal book_date" id="courseDates">
  <i class="close icon"></i>
  <a class="ui blue label" style="margin-left: -10px; margin-top: 10px;"><h4 class="ui header" style="color:white">Ticket Information</h4></a>
  <div class="content" style="padding-top:0px;">
    <h3><%= @course.name%></h3>
    <div class="ui segment" style="padding-top:0px;">
      <ul class="course-dates">
      <li class="header" style="padding-bottom: 0px;">
        <div class="ui grid">
          <div class="five wide column">Date & Location</div>
          <div class="four wide column center" style="padding-top:1rem !important">Ticket</div>
          <div class="two wide column center">Price</div>
          <div class="five wide column center">Book Date</div>
        </div>
        <div class="ui divider"></div>
      </li>
      <% if @course.upcoming_date == nil %>
        <h3>There are no course dates available for this course yet</h3>
      <% else %>
      <% @course.upcoming_dates.each do |date|%>
      <li>
        <div class="ui grid">
          <div class="five wide column">
            <i class="calendar icon"></i>
            <%= date.start_date.strftime("%d/%m/%Y") %>
            <br>
            <br>
            <i class="marker icon"></i>
            <%= date.course.address.truncate(10) %>
          </div>
          <div class="eleven wide column center" style="padding: 0px; padding-top: 1rem;">
            <% date.tickets.each do |ticket| %>
              <div class="row" style="display: block; width: 100%; min-height: 50px; margin-bottom: 10px;">
                <p style="text-transform:lowercase;display:inline-block;float:left;width:34%;max-width: 34%;"><%= ticket.name %></p>
                <p style="text-transform:lowercase;display:inline-block;float:left;width:25%;max-width: 25%;"><%= number_to_currency(ticket.price, :precision => 2, :unit => "£")%></p>
                <% if ticket.places_left <= 0%>
                  Sold Out!
                <% else %>
                  <% if ticket.number_of_dates > 1 %>
                    <%= link_to("Choose Dates", new_ticket_payment_path(ticket.id), :class => "ui positive labeled button", :style => "display:inline-block;float: right; width:37%; max-width:37%;" )%>
                  <% else %>
                    <%= link_to("Book Now", new_ticket_payment_path(ticket.id), :class => "ui positive button", :style => "display:inline-block;float: right; width:37%; max-width:37%;", :id => "bookDate" )%>
                  <% end %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="ui divider"></div>
      </li>

      <br>
      <% end %>
      <% end %>
      <ul>
    </div>
  </div>
</div>

app/views/courses/_company_bio.html.erb
<div class="ui items segment" style="padding-top:1rem">
    <a class="ui blue ribbon label">BROUGHT TO YOU BY</a>
    <div class="item">
        <div class="image">
            <!-- <img src="img/chef300.png"> -->
            <%= image_tag(@course.user.avatar_url(:medium), :class => "ui medium rounded course-image" )%>
        </div>
    </div>
    <div class="item">
        <div class="content centred">
            <a class="header"><%= @course.user.company_name %></a>
            <div class="description">
                <%# truncate(@user.description.html_safe, :length => 150)%>
            </div>
        </div>
    </div>
    <div class="item content centred">
        <!-- <div class="ui tiny statistic">
            <div class="value">256</div>
            <div class="label">HOURS <br>TAUGHT</div>
        </div>
        <div class="ui tiny statistic">
            <div class="value">23</div>
            <div class="label">CLASSES <br>TAUGHT</div>
        </div>
        <div class="ui tiny statistic">
            <div class="value">402</div>
            <div class="label">PEOPLE <br>TAUGHT</div>
        </div> -->
    </div> <!-- .content -->    <!-- .item -->
</div> <!-- .ui.items -->

app/views/courses/_confirmation_email_fields.html.erb
<div class="ui form time-select" style="margin: auto;">
	<div class="fields">
  	<h3></h3>
  	<div class="field" style="width: 100%;">
      <%= form.cktext_area :content %>
  	</div>
  	<div class="field four wide">
  	</div>
  	<div class="field four wide">
  	</div>
  	<div class="field four wide">
  	</div>
  </div>
</div>

app/views/courses/_course_date_fields.html.erb
<div class="ui form time-select" style="max-width: 85%; margin: auto;">
	<div class="four fields">
  	<h3>Date & time</h3>
  	<div class="field four wide">
  		<%= form.text_field :start_date, :placeholder => "11/02/2015"%>
  	</div>
  	<div class="field four wide">
  		<%= form.time_select :start_time, :class => "time-select" %>
      <span>-</span>
  	</div>
  	<div class="field four wide">
  		<%= form.text_field :end_date, :placeholder => "11/02/2015" %>
  	</div>
  	<div class="field four wide">
  		<%= form.time_select :end_time %>
  	</div>
  </div>
</div>
<div class="ui divider" style="margin-top: 100px; margin-bottom: 25px;"></div>
<div class="ui circular labels">
  <a class="ui label" style="display:inline-block; font-size: 1.8571rem;">
    3
  </a>
  <h2 style="display:inline-block">Create Tickets</h2>
</div>
<%= form.fields_for :tickets do |builder| %>
  <% render 'ticket_fields', form: builder %>
<% end %>

app/views/courses/_course_dates.html.erb
<div class="ui form time-select" style="max-width: 85%; margin: auto;">
	<div class="four fields">
  	<h3>Date & time</h3>
  	<div class="field four wide">
  		<%= form.text_field :start_date, :placeholder => "11/02/2015"%>
  	</div>
  	<div class="field four wide">
  		<%= form.time_select :start_time, :class => "time-select" %>
  	</div>
  	<div class="field four wide">
  		<%= form.text_field :end_date, :placeholder => "11/02/2015" %>
  	</div>
  	<div class="field four wide">
  		<%= form.time_select :end_time %>
  	</div>
  </div>
  <div class="fields">
  	<h3>Number of tickets</h3>
  	<div class="field three wide">
  		<%= form.text_field :quantity, :placeholder => "20" %>
  	</div>
  </div>
</div>
<%= form.fields_for :tickets do |builder| %>
  <%= render 'tickets_form', :form => builder %>
<% end %>

app/views/courses/_edit_course_fields.html.erb
<div class="ui form" style="max-width: 73%; margin: auto;">
  <div class="field">
    <label>Course title <span style="font-weight: 100;">(max 30 characters)</span></label>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <label>Course description</label>
    <%= form.cktext_area :description, :id => "description" %>
  </div>
  <div class="field">
    <label>What to wear</label>
    <%= form.text_field :what_to_wear %>
  </div>
  <div class="field">
    <label>What to bring</label>
    <%= form.text_field :what_to_bring %>
  </div>
  <div class="field">
    <label>Experience needed</label>
    <%= form.text_field :experience %>
  </div>
  <div class="field">
    <label>Course Category</label>
    <%= form.select :category, options_for_select([["Arts & Crafts", "arts"], ["Food & Drink","food"],["Health & Wellbeing", "health"],["Music", "music"],["Outdoor Education", "outdoor"],["Other", "other"]])%>
  </div>
  <%= form.fields_for :course_addresses do |addresses_form| %>
	  <div class="two fields">
	  	<h3>Location</h3>
	    <div class="field">
	      <%= addresses_form.text_field :address1, :placeholder => 'Address 1'%>
	    </div>
	    <div class="field">
	      <%= addresses_form.text_field :address2, :placeholder => 'Addres 2' %>
	    </div>
	    <div class="field">
	      <%= addresses_form.text_field :city, :placeholder => 'City/Town' %>
	    </div>
	    <div class="field four wide">
	      <%= addresses_form.text_field :postcode, :placeholder => 'Postcode'%>
	    </div>
	  </div>
  <% end %>
  <div class="field">
  	<h3>Course image</h3>
  	<div class="ui styled fluid accordion">
	    <div class="active title">
	      <i class="dropdown icon"></i>
	      Current image
	    </div>
	    <div class="active content">
			  <%= image_tag @course.avatar.medium %>
	    </div>
	    <div class="title">
	      <i class="dropdown icon"></i>
	      Replace Image
	    </div>
	    <div class="content">
		  	<img id="blah" src="#" alt="" class="ui small bordered image" style="min-width: 150px; min-height: 150px; margin-bottom: 16px;"/>
		  	<%= form.file_field :avatar, :id => "imgInp" %>
		   	<%= form.hidden_field :avatar_cache %>
	    </div>
	  </div>
  </div>
</div>

app/views/courses/_new_courses_form.html.erb
<div class="column thirteen wide">
	<div class="course-form" style="width: 80%; margin:auto">
	<%= form_for @course, :multipart => true, :html => {:class => 'ui form fluid '} do |form|  %>
		<div class="ui segment" style="display:block">
			<h2 style="display:inline-block">Create a course in 3 easy steps </h2>
			<div class="ui divider" style="margin-top: 50px; margin-bottom: 25px;"></div>
			<div class="ui circular labels">
			  <a class="ui label" style="display:inline-block; font-size: 1.8571rem;">1</a>
				<h2 style="display:inline-block">Course details</h2>
			</div>
				<%= render 'course_fields', form: form %>
				<div class="ui divider" style="margin-top: 100px; margin-bottom: 25px;"></div>
				<div class="ui circular labels">
				  <a class="ui label" style="display:inline-block; font-size: 1.8571rem;">2</a>
					<h2 style="display:inline-block">Create date</h2>
				</div>
				<%= form.fields_for :course_dates do |builder| %>
			    <%= render 'course_date_fields', form: builder %>
			  <% end %>
			  <div class="ui divider" style="margin-top: 100px; margin-bottom: 25px;"></div>
				<div class="ui circular labels">
				  <a class="ui label" style="display:inline-block; font-size: 1.8571rem;">4</a>
					<h2 style="display:inline-block">Extras</h2>
				</div>
				<div class="ui styled fluid accordion">
			    <div class="title">
			      <i class="dropdown icon"></i>
			      Extra Content to Accompany Confirmation Email
			    </div>
			    <div class="content">
			    	<h2>Please add some content to add to the confirmation email</h2>
					  <%= form.fields_for :confirmation_emails do |builder| %>
					  	<%= render 'confirmation_email_fields', form: builder %>
					  <% end %>
			    </div>
			  </div>
				<div class="ui segment no-box-shadow" style="margin-top: 40px;">
					<div class="ui dimmer courseLoader">
            <div class="ui indeterminate text loader">Creating Course</div>
          </div>
					<%= form.submit :id => "courseSubmit", :style =>"float:right; width:250px", :class => "ui inverted green button" %>
					<div class="ui error message" style="margin-top:50px;"></div>
				</div>
			<% end %>
		</div>
	</div>
</div>

<script>
	function readURL(input) {
	  if (input.files && input.files[0]) {
	    var reader = new FileReader();
	    reader.onload = function (e) {
		    $('#blah').attr('src', e.target.result);
				}
	    reader.readAsDataURL(input.files[0]);
	  }
	}
	$("#imgInp").change(function(){
	    readURL(this);
	});
</script>

app/views/courses/_terms_and_conditions_modal.html.erb
<div class="ui modal" id="termsAndConditions">
  <i class="close icon"></i>
  <div class="header">
    Profile Picture
  </div>
  <div class="content">
    <div class="ui medium image">
      <img src="">
    </div>
    <div class="description">
      <div class="ui header">We've auto-chosen a profile image for you.</div>
      <p>We've grabbed the following image from the <a href="https://www.gravatar.com" target="_blank">gravatar</a> image associated with your registered e-mail address.</p>
      <p>Is it okay to use this photo?</p>
    </div>
  </div>
  <div class="actions">
    <div class="ui black button">
      Nope
    </div>
    <div class="ui positive right labeled icon button">
      Yep, that's me
      <i class="checkmark icon"></i>
    </div>
  </div>
</div>

app/views/courses/_ticket_fields.html.erb
<div class="ticket table" style="margin-top:40px;">
  <div class="ticket table row" style="border-bottom: 1px solid #d4d4d5;">
    <div class"ticket-header" style="display:table-cell; width:31%; vertical-align:middle; padding:0.7em 0.8em;">Ticket name</div>
    <div class"ticket-header" style="display:table-cell; width:20%; vertical-align: middle; padding:0.7em 0.8em;">Price</div>
    <div class"ticket-header" style="display:table-cell; width:18%; vertical-align: middle; padding:0.7em 0.8em;">Quantity</div>
    <div class"ticket-header" style="display:table-cell; width:18%; vertical-align: middle; padding:0.7em 0.8em; text-align:center"><i class="circular absorb_info info icon link" data-content="Attendee will not pay the booking fee, instead you will absorb it" style="margin-right:10px;"></i>Absorb Fee</div>
    <div class"ticket-header" style="display:table-cell; width:15%; vertical-align: middle; padding:0.7em 0.8em; text-align:center">More</div>
  </div>
  <div class="table row" style="height:50px; display:table; width:100%;">
    <div class"table-header" style="display:table-cell; width:31%; vertical-align: middle;   padding: 0.7em 0.8em;"><%= form.text_field :name, :placeholder => "Early Bird, First Release" %></div>
    <div class"table-header" style="display:table-cell; width:20%; vertical-align: middle;   padding: 0.7em 0.8em;"><%= form.text_field :price, :placeholder => "20.00" %></div>
    <div class"table-header" style="display:table-cell; width:18%; vertical-align: middle;   padding: 0.7em 0.8em;"><%= form.text_field :quantity, :placeholder => "100"%></div>
    <div class"table-header" style="display:table-cell; width:18%; vertical-align: middle;   padding: 0.7em 0.8em; text-align:center"><div class="ui toggle checkbox" style="display:inline-block; margin-left:15px;">
        <%= form.check_box :absorb_fee, :type =>"radio" %>
      </div></div>
    <div class"table-header" style="display:table-cell; width:15%; vertical-align: middle;   padding: 0.7em 0.8em;">
      <div id="detailedTicket" style="text-align:center">
        <i class="setting icon" style="font-size:2rem;"></i>
      </div>
    </div>
  </div>
  <div class="table row" id="moreTicket" style="padding: 0.7em 0.8em;">
    <div class="multiple-dates" style="display:block; margin-top:18px;">
      <label><i class="circular absorb_info info icon link" data-content="If a attendee needs to book multiple dates at a time then add the number of dates here." style="margin-right:10px;"></i>Multiple Dates</label>
      <div class="ui toggle checkbox" id="numberDates" style="display:inline-block; margin-left:15px;">
        <input type="checkbox" class="ui toggle checkbox" id="numberDates">
      </div>
      <div id="numberDatesField">
        <%= form.text_field :number_of_dates, :placeholder => "100"%>
      </div>
    </div>
    <br>
  </div>
</div>

app/views/courses/crop.html.erb
<%= render "crop_image_modal" %>
<div class="ui segment">
    <div class="ui circular labels" style="display:inline-block">
      <a class="ui label" style="display:inline-block; font-size: 1.8571rem;">
        3
      </a>
        <h2 style="display:inline-block">Preview Course details</h2>
    </div>
    <div class="edit-option-buttons">
        <%= form_for @course do |f| %>
            <% %w[x y w h].each do |attribute| %>
                <%# f.text_field "crop_#{attribute}", id: "crop_#{attribute}"%><br>
                <%= f.hidden_field "crop_#{attribute}" %>
            <% end %>
            <%= f.submit "Save", :class => "ui inverted green button", :style =>"float:right; width:150px"%>
        <% end %>
        <div id="cropModal" class="ui inverted blue button" style="float:right; width:150px">Crop</div>
        <%= link_to("Edit Text", edit_course_path(@course.id), :class => "ui inverted orange button", :style =>"float:right; width:150px") %>
    </div>
</div>
<div class="ui segment course-info" style="margin: 0px; background:none">
<div class="ui pusher stackable padded grid text">
       <%# render "book_date" %>
        <!-- LEFT CONTENT -->
        <div class="ten wide column" style="height:100%;">
            <div class="ui segment items">
                <div class="item">
                    <div class="image" style="width:300px;">
                        <%= image_tag(@course.avatar_url(:medium), :class => "ui medium rounded course-image" )%>
                    </div>
                    <div class="content centred">
                        <div class="ui list">
                            <div class="item">
                                <a><h3 class="ui header" style="font-size:2rem"><%= @course.name.capitalize %></h3></a>
                            </div>
                            <div class="item" style="padding: 0.72em 0em;">
                                <a style="font-size:1.5rem">
                                    <i class="calendar icon"></i><%= @course.upcoming_date.start_date.strftime("%A, %b %d") %>
                                </a>
                            </div>
                            <div class="item" style="padding: 0.72em 0em;">
                                <a style="font-size:1.5rem">
                                    <i class="clock icon"></i><%= @course.upcoming_date.start_time.strftime("%l:%M %p")%> - <%= @course.upcoming_date.end_time.strftime("%l:%M %p")%>
                                </a>
                            </div>
                            <div class="item" style="padding: 0.38em 0em;">
                              <a style="font-size:1.5rem; margin-left: 8px;">
                                <%# number_to_currency(@course.price, :precision => 2, :unit => "£")  %>
                              </a>
                            </div>
                        </div>
                        <!-- <br> -->
                        <div class="item secure">
                            <h6 class="secure-spot">SECURE A SPOT IN THIS COURSE</h6>
                        </div>
                        <div class="item">
                            <a><div id="course" class="massive ui button book-now positive">BOOK NOW</div></a>
                        </div>
                    </div> <!-- .content -->
                </div> <!-- .item -->
            </div> <!-- .ui.items -->
            <div class="ui segment items" style="margin-bottom: 1.5em !important;">
                <h3 class="ui header">ABOUT THIS COURSE</h3>
                <%= @course.description.html_safe%>
            </div>
        </div> <!-- .column -->
        <!-- END OF LEFT CONTENT -->
        <!-- RIGHT CONTENT -->
        <div class="six wide column">
            <div class="ui segment">
                <% @course.course_addresses.each do |address|%>
                <h5 class="ui top attached header address"><%= address.address1 %>, <%= address.address2 %>, <%= address.city %>, <%= address.postcode %></h5>
                <div class="ui attached segment compass">
                  <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{address.latitude}%2C#{address.longitude}", :class => "map_style" %>
                </div>
                <% end %>
                <div class="ui style fluid accordion">
                    <div class="title" style="border-bottom: 1px solid black">
                        <i class="dropdown icon"></i>
                        WHAT TO BRING?
                    </div>
                    <div class="content">
                        <p><%= @course.what_to_bring %></p>
                    </div>
                    <br>
                    <div class="title" style="border-bottom: 1px solid black">
                        <i class="dropdown icon"></i>
                        WHAT TO WEAR?
                    </div>
                    <div class="content">
                        <p><%= @course.what_to_wear %></p>
                    </div>
                    <br>
                    <div class="title" style="border-bottom: 1px solid black">
                        <i class="dropdown icon"></i>
                        EXPERIENCE NEEDED?
                    </div>
                    <div class="content">
                        <p><%= @course.experience %></p>
                    </div>
                </div>
            </div>
            <!-- END OF ACCORDION -->
            <!-- BROUGHT TO YOU BY -->
            <%= render "company_bio" %>
        </div> <!-- .column -->
    </div>
</div>

app/views/courses/edit.html.erb
<div class="column thirteen wide">
	<div class="course-form" style="width: 80%; margin:auto">
	<%= form_for @course, :multipart => true, :html => {:class => 'ui form fluid '} do |form|  %>
		<div class="ui segment" style="display:block">
			<h2 style="display:inline-block">Create a course in 3 easy steps </h2>
			<div class="ui divider" style="margin-top: 50px; margin-bottom: 25px;"></div>
			<div class="ui circular labels">
			  <a class="ui label" style="display:inline-block; font-size: 1.8571rem;">1</a>
				<h2 style="display:inline-block">Course details</h2>
			</div>
				<%= render 'edit_course_fields', form: form %>
				<div class="ui divider" style="margin-top: 100px; margin-bottom: 25px;"></div>
				<div class="ui circular labels">
				  <a class="ui label" style="display:inline-block; font-size: 1.8571rem;">4</a>
					<h2 style="display:inline-block">Extras</h2>
				</div>
				<div class="ui styled fluid accordion">
			    <div class="title">
			      <i class="dropdown icon"></i>
			      Extra Content to Accompany Confirmation Email
			    </div>
			    <div class="content">
			    	<h2>Please add some content to add to the confirmation email</h2>
					  <%= form.fields_for :confirmation_emails do |builder| %>
					  	<%= render 'confirmation_email_fields', form: builder %>
					  <% end %>
			    </div>
			  </div>
				<div class="ui divider" style="margin-top: 100px; margin-bottom: 25px;"></div>
				<div class="ui segment no-box-shadow" style="margin-top: 40px;">
					<div class="ui dimmer courseLoader">
            <div class="ui indeterminate text loader">Creating Course</div>
          </div>
					<%= form.submit :id => "courseSubmit", :style =>"float:right; width:250px", :class => "ui inverted green button" %>
					<div class="ui error message" style="margin-top:50px;"></div>
				</div>
			<% end %>
		</div>
	</div>
</div>



<script>
	  function readURL(input) {
	    if (input.files && input.files[0]) {
	        var reader = new FileReader();

	        reader.onload = function (e) {
	            $('#blah').attr('src', e.target.result);
	        }

	        reader.readAsDataURL(input.files[0]);
	    }
	}

	$("#imgInp").change(function(){
	    readURL(this);
	});
</script>

app/views/courses/new.html.erb
<!-- this is the modal that has all the terms and conditions in it -->
<%= render "terms_and_conditions_modal" %>

<!-- this is the form for creating a new course -->
<%= render "new_courses_form" %>

app/views/courses/preview.html.erb
<p>
  <strong>Address:</strong>
  <% @course.course_addresses.each do |address| %>
</p>
<p>
  <strong>Latitude:</strong>
  <%= address.latitude %>
</p>
<p>
  <strong>Longitude:</strong>
  <%= address.longitude %>
</p>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{address.latitude}%2C#{address.longitude}" %>

<% end %>