config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root "pages#home_page"

  resources :courses do
    resources :course_dates do
      member do
        get 'course_details'
      end
      resources :tickets do
        resources :entries
      end
    end
  end

  resources :tickets do
    resources :payments
  end

  resources :course_dates do
    resources :bookings
  end

  resources :payments

  resources :booking_dates

  resources :plans
  resources :subscriptions

  devise_for :users

  get 'users/course_providers', :to => 'users#course_providers_index'
  get 'users/:id/calendar', :to => 'users#calendar'

  resources :users, :only => [:show, :edit, :update, :index] do
  end

  resource :dashboard do
    get 'months_bookings_csv'
    get 'all_bookings_csv'
    get 'transactions'
    get 'weeks_transactions_csv'
    get 'weeks_bookings_csv'
    get 'months_transactions_csv'
    get 'all_transactions_csv'
    get 'bookings'
    get 'withdraw'
  end

  get '/about', :to => 'pages#about'
  get '/faq', :to => 'pages#faq'
  get '/sales_and_refunds', :to => 'pages#sales_and_refunds'
  get '/offer', :to => 'pages#offer'
  get '/home', :to => 'pages#home_page'
  get '/how_it_works', :to => 'pages#how_it_works'
  get '/examples', :to => 'pages#examples'

end

app/models/course_date.rb
class CourseDate < ActiveRecord::Base
	has_many :payments
	has_many :booking_dates
	after_create :send_course_info
	belongs_to :course
  has_many :tickets, dependent: :destroy
  accepts_nested_attributes_for :tickets

	def valid_dates(course)
		if course.start_date_time > Time.now && course.active?
			course
		end
	end

	def start_date_time
		d = start_date
		t = start_time
		dt = DateTime.new(d.year, d.month, d.day, t.hour, t.min, t.sec, t.zone)
	end

	def invalid
		@time = self.start_date_time - 24.hours
		self.delay_until(@time).update_attributes(active: false)
	end

	def full
		self.booking_dates.count >= self.tickets.last.quantity
	end

	def not_full
		self.booking_dates.count < self.tickets.last.quantity
	end

	def send_course_info
		@course_date = self.start_date_time
		CourseDateMailer.delay_until(@course_date - 1.days).course_info(self.id)
	end

	def pretty_date
		start_date.strftime("%m/%d/%Y/") + start_time.strftime("%I:%M%p")
	end

	def select_date
		start_date_time.strftime("%A, %d %b %Y %l:%M %p")
	end

	def select_start_end_date
		start_date_time.strftime("%A, %d %b %Y %l:%M %p") + " to " + end_time.strftime("%l:%M %p")
	end

	def max_revenue
		quantity * self.course.price
	end

	def sale_percentage
		value = self.payments.count.to_f / quantity * 100.00
		value.to_i
	end

	def send_new_date
		CourseDateMailer.new_date(self).deliver!
	end

	def max_tickets
		@tickets = []
		self.tickets.each {|ticket| @tickets <<  ticket.quantity}
		@tickets.inject(:+)
	end

	def tickets_left
		self.booking_dates.count.to_s  + "/" + self.max_tickets.to_s
	end

	def revenue
		@ticket_ammount = []
		@revenue = []
		self.tickets.each do |ticket|
			@revenue <<  ticket.bookings * ticket.price
		end
		@revenue.inject(:+)
	end

	def all_attendees
		@payments = self.payments.map {|p| p}
		@entry_selections = self.entry_selections.map {|e| e}
		@all = @entry_selections + @payments
		raise @all.inspect
	end

end

app/controllers/course_dates_controller.rb
class CourseDatesController < ApplicationController
	before_action :fetch_and_authorize_course, :except => [:index]

	def new
		@course_date = @course.course_dates.build
		@course_date.tickets.build
	end

	def create
		@course_date = @course.course_dates.create(params[:course_date].permit(:start_date, :start_time, :end_date, :end_time, :course_id, tickets_attributes:[:course_date_id, :name, :price, :quantity, :absorb_fee, :number_of_dates]))
		if @course_date.save
			redirect_to dashboard_path(@course_date.course.user.id)
			flash[:notice] = 'New Course Date Created'
		else
			raise "error"
		end
	end

	def edit
		@course_date = CourseDate.find(params[:id])
	end

	def course_details
		@course_date = @course.course_dates.find(params[:id])
		@payments = @course_date.payments
		@course_date.tickets_left
		@percentage = (@course_date.booking_dates.count.to_f /  @course_date.max_tickets.to_f)
		gon.percentage = @percentage
		@user = current_user
	end

	def update
		@course_date = CourseDate.find(params[:id])
		if @course_date.update_attributes(params[:course_date].permit(:start_date, :start_time, :end_date, :end_time, :course_id, tickets_attributes:[:id, :name, :course_date_id, :price, :quantity, :absorb_fee, :number_of_dates]))
			redirect_to course_details_course_course_date_path(@course_date.course_id, @course_date.id)
		else
			render :edit
		end
	end

	def index
		@active_course_dates = []
		CourseDate.all.each  do |d|
			if d.start_date_time > DateTime.now && d.course.private? == false
				@active_course_dates << d
			end
		end
		@course_dates = @active_course_dates.sort_by do |course_date|
			course_date.start_date_time
		end
	end

	private

	def fetch_and_authorize_course
		@course = Course.find(params[:course_id])
		raise 'Unauthorized' unless @course.user == current_user
	end

end

app/helpers/course_dates_helper.rb
module CourseDatesHelper
end

app/views/course_dates/_attendees.html.erb
<h1 class="header" style="margin-bottom: 35px;">Attendees</h1>
<table class="ui very basic table attendees-table" style="width: 94%; margin: auto;">
  <thead>
    <tr>
      <th>Full name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Paid on</th>
      <th style="text-align:center">Actions</th>
      <th style="text-align:center">Edit Details</th>
    </tr>
  </thead>
  <tbody>
    <% @course_date.booking_dates.each do |date| %>
      <tr>
        <td class="attendee-name"><%= date.booking.name %></td>
        <td><%= date.booking.email %></td>
        <td><%= date.booking.contact_number %></td>
        <td><%= date.booking.created_at.strftime("%d/%m/%Y")%></td>
        <td style="text-align:center">
          <% if @course_date.start_date > DateTime.now %>
            <%= link_to 'Transfer Date', booking_date_path(date), :class => "ui inverted red button" %>
          <% end %>
        </td>
        <td style="text-align:center">
          <% if @course_date.start_date > DateTime.now %>
            <%= link_to 'Edit', edit_course_date_booking_path(@course_date, date.booking.id), :class => "ui inverted blue button" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/course_dates/_course_details.html.erb
<div class="two column stackable ui grid" style="margin:0px;">
    <div class="column sixteen wide">
        <div class="ui segment" style="padding:1rem">
            <h1 style="margin:0px;"><%= @course_date.course.name %></h1>
        </div>
    </div>
    <!-- LEFT SIDE -->
    <div class="column five wide">
        <div class="ui segment">
            <div class="column">
                <div class="image">
                    <%= image_tag(@course_date.course.avatar_url(:medium))%>
                </div>
            </div>
            <div class="column">
                SPACES LEFT: <%= @course_date.quantity %>
            </div>
            <br>
            <div class="column">
                DATE: <%= @course_date.start_date.strftime('%d/%m/%Y') %>
            </div>
            <BR>
            <div class="column">
                <%= link_to("Edit Date", edit_course_course_date_path(@course_date.course.id, @course_date.id), :class => "ui button", :style =>"display:block") %>
                <!-- <a><div id="course" class="ui button" style="display:block">EDIT COURSE DATE</div></a> -->
            </div>
        </div>
    </div>
    <!-- END OF LEFT SIDE -->
    <!-- RIGHT SIDE -->
    <div class="column eleven wide">
        <div class="ui segment">
            <!-- START OF THE TABLE -->
            <h3 style="margin:0px;">ATTENDEES</h3>
            <table class="ui striped table" style="min-height: 285px;">
                <thead style="display:block">
                    <tr>
                        <th class="one wide">
                            #
                        </th>
                        <th class="seven wide">
                            Name
                        </th>
                        <th class="two wide center aligned">
                            Email
                        </th>
                        <th class="two wide center aligned">
                            Telephone
                        </th>
                        <th class="three wide center aligned">
                            Tickets
                        </th>
                        <th class="one wide center aligned">
                            Paid on
                        </th>
                    </tr>
                </thead>
                <tbody style="display: block; max-height: 208px; overflow-y: auto">
                		<% @course_date.payments.each do |payment| %>
                            <tr style="display:block">
                                <td class="one wide collapsing">1</td>
                                <td class="seven wide left aligned"><%= payment.full_name %></td>
                                <td class="two wide left aligned"><%= payment.email %></td>
                                <td class="two wide center aligned"><%# course_date.payments.count %>/<%# course_date.quantity%></td>
                                <td class="three wide center aligned"><%# course_date.max_revenue %></td>
                                <td class="one wide center aligned"><%= payment.created_at.strftime("%d/%m/%Y")%></td>
                            </tr>
                        <% end %>
                </tbody>
            </table>
            <!-- END OF THE TABLE -->
            <div class="ui segment">
                <div class="ui two column stackable grid">
                    <div class="column">
                        <a><div id="course" class="ui button" style="display:block">NEW DATE</div></a>
                    </div>
                    <div class="column">
                        <a><div id="course" class="ui button" style="display:block">EMAIL ALL ATTENDEES</div></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END OF RIGHT SIDE -->
    <div class="column five wide">
        <div class="ui raised segment">
            <a class="ui red ribbon label">PAYMENT STATUS</a>
            <div class="ui teal progress" id="example2" data-attibute="<%= @course_date %>" style="margin-top:10px;">
                <div class="bar"></div>
                <div class="label"><%= @course_date.sale_percentage %>% Full</div>
            </div>
        </div>
    </div>
    <div class="column eleven wide">
        <div class="ui segment">
            <h1 style="margin: 0px; text-align: center">Payments</h1>
            <!-- AT THE MOMENT THIS GRAPH SHOWS YOU THE NUMBER OF COURSES CREATED FROM THE BEGINNING OF THE MONTH -->
                <%= line_chart @course_date.payments.group_by_day(:created_at, range: Date.today.beginning_of_month..Time.now).count %>
            <!-- END OF THE GRAPH -->

        </div>
    </div>
</div>

app/views/course_dates/_summary.html.erb
<div class="row">
	<h2 class="header" style="margin-bottom: 44px;">Course Date Summary</h2>
	<div class="ui two column stackable grid">
    <div class="column six wide">
    	<h3 class="header sub-heading" style="margin-top:0px;">Tickets sold: <%= @course_date.tickets_left %></h3>
    </div>
    <div class="column ten wide">
    	<div class="ui teal progress" id="example2" data-attibute="<%= @course_date.tickets_left %>" style="width: 75%;">
        <div class="bar"></div>
      </div>
    </div>
  </div>
  <div class="column">
  	<h3 class="header sub-heading">Revenue: <%= number_to_currency(@course_date.revenue, :precision => 2, :unit => "£")  %></h3>

  </div>
</div>

app/views/course_dates/_ticket_fields_new.html.erb
<div class="ticket table" style="margin-top:40px;">
  <div class="ticket table row" style="border-bottom: 1px solid #d4d4d5;">
    <div class"ticket-header" style="display:table-cell; width:31%; vertical-align:middle; padding:0.7em 0.8em;">Ticket name</div>
    <div class"ticket-header" style="display:table-cell; width:20%; vertical-align: middle; padding:0.7em 0.8em;">Price</div>
    <div class"ticket-header" style="display:table-cell; width:18%; vertical-align: middle; padding:0.7em 0.8em;">Quantity</div>
    <div class"ticket-header" style="display:table-cell; width:18%; vertical-align: middle; padding:0.7em 0.8em; text-align:center"><i class="circular absorb_info info icon link" data-content="Attendee will not pay the booking fee, instead you will absorb it" style="margin-right:10px;"></i>Absorb Fee</div>
    <div class"ticket-header" style="display:table-cell; width:15%; vertical-align: middle; padding:0.7em 0.8em; text-align:center">More</div>
  </div>
  <div class="table row" style="height:50px; display:table; width:100%;">
    <div class"table-header" style="display:table-cell; width:31%; vertical-align: middle;   padding: 0.7em 0.8em;"><%= form.text_field :name, :placeholder => "Early Bird, First Release" %></div>
    <div class"table-header" style="display:table-cell; width:20%; vertical-align: middle;   padding: 0.7em 0.8em;"><%= form.text_field :price, :placeholder => "20.00" %></div>
    <div class"table-header" style="display:table-cell; width:18%; vertical-align: middle;   padding: 0.7em 0.8em;"><%= form.text_field :quantity, :placeholder => "100"%></div>
    <div class"table-header" style="display:table-cell; width:18%; vertical-align: middle;   padding: 0.7em 0.8em; text-align:center"><div class="ui toggle checkbox" style="display:inline-block; margin-left:15px;">
        <%= form.check_box :absorb_fee, :type =>"radio" %>
      </div></div>
    <div class"table-header" style="display:table-cell; width:15%; vertical-align: middle;   padding: 0.7em 0.8em;">
      <div id="detailedTicket" style="text-align:center">
        <i class="setting icon" style="font-size:2rem;"></i>
      </div>
    </div>
  </div>
  <div class="table row" id="moreTicket" style="padding: 0.7em 0.8em;">
    <div class="multiple-dates" style="display:block; margin-top:18px;">
      <label><i class="circular absorb_info info icon link" data-content="If a attendee needs to book multiple dates at a time then add the number of dates here." style="margin-right:10px;"></i>Multiple Dates</label>
      <div class="ui toggle checkbox" id="numberDates" style="display:inline-block; margin-left:15px;">
        <input type="checkbox" class="ui toggle checkbox" id="numberDates">
      </div>
      <div id="numberDatesField">
        <%= form.text_field :number_of_dates, :placeholder => "100"%>
      </div>
    </div>
    <br>
  </div>
</div>

app/views/course_dates/course_details.html.erb
<div class="two column stackable ui grid dashboard course-details-dash" style="background-color: #36464f;">
	<div class="column four wide">
		<%= render "layouts/course_details_sidenav" %>
	</div>
	<div class="column twelve wide" style="background:white; min-height: 420px;">
		<div class="row" style="padding-bottom: 20px;">
			<h1 class="header"><%= @course_date.course.name %></h1>
			<%= link_to("Edit Date", edit_course_course_date_path(@course_date.course.id, @course_date.id), :class => "ui inverted green button edit") %>
			<h3 class="header sub-heading"><%= @course_date.start_date_time.strftime("%A, %d %b %Y %l:%M %p") %></h3>
		</div>
		<div class="ui pointing secondary menu">
	    <a class="active item" data-tab="first" style="width:50%; text-align:center;font-size: 18px;">Summary</a>
	    <a class="item" data-tab="second" style="width:50%%; text-align:center;font-size: 18px;">Attendees</a>
	  </div>
		<div class="ui active tab" data-tab="first">
			<%= render "summary" %>
		</div>
		<div class="ui tab" data-tab="second">
			<%= render "attendees" %>
		</div>
	</div>
</div>

app/views/course_dates/edit.html.erb
<div class="course-form" style="width: 80%; margin:auto">
		<%= form_for [@course, @course_date], :multipart => true, :html => {:class => 'ui form fluid '} do |course_date_form|  %>
	<div class="ui segment" style="display:block">
		<h2 style="display:inline-block">Edit course date </h2>
		<%= course_date_form.submit :style =>"float:right; width:250px; display:inline-block; margin: 2rem 0em", :class => "ui inverted green button" %>
		<div class="ui divider" style="margin-top: 50px; margin-bottom: 25px;"></div>
		<div class="ui circular labels">
		  <a class="ui label" style="display:inline-block; font-size: 1.8571rem;">
		    1
		  </a>
			<h2 style="display:inline-block">Course date</h2>
		</div>
			<div class="ui form edit-date" style="max-width: 73%; margin: auto;">
				<div class="four fields">
			  	<h3>Date & time</h3>
			  	<div class="field four wide">
			  		<%= course_date_form.text_field :start_date, :placeholder => "11/02/2015" %>
			  	</div>
			  	<div class="field four wide">
			  		<%= course_date_form.time_select :start_time %>
			  	</div>
			  	<div class="field four wide">
			  		<%= course_date_form.text_field :end_date, :placeholder => "11/02/2015" %>
			  	</div>
			  	<div class="field four wide">
			  		<%# course_date_form.time_select :end_time, :placeholder => "19:30" %>
			  		<%= course_date_form.time_select :end_time %>
			  	</div>
			  </div>
			  <%= course_date_form.fields_for :tickets do |builder| %>
			  	<% render 'ticket_fields_new', form: builder %>
		  	<% end %>
			</div>
			<div class="ui divider" style="margin-top: 100px; margin-bottom: 25px;"></div>
			<div class="ui segment">
				<%= course_date_form.submit :style =>"float:right; width:250px", :class => "ui inverted green button" %>
			</div>
		<% end %>
	</div>
</div>

app/views/course_dates/index.html.erb
<div class="ui special cards container course-dates">
    <% @course_dates.each do |course_date| %>

        <div class="card element-item">

            <div class="ui dimmable image">
              <% if course_date.full %>
                <a class="ui left red corner label" style="font-size: 1.5rem; text-align: left;">
                  <span style="font-size: 1rem; -webkit-transform: rotate(90deg); -moz-transform: rotate(90deg); -o-transform: rotate(90deg); -ms-transform: rotate(90deg); transform: rotate(315deg); position: inherit; top: 30%;">
                    Sold out
                  </span>
                </a>
              <% end %>

                <!-- end of sold out banner -->
              <div class="ui dimmer">
                <div class="content">
                  <div class="ui list">
                    <div class="item"><i class="user icon"></i><%= course_date.course.user.company_name.truncate(27) %></div>
                    <div class="item"><i class="compass icon"></i><%= course_date.course.address.truncate(27) %></div>
                    <div class="item"><i class="tag icon"></i><%= course_date.course.category %></div>
                    <div class="item center">
                      <%= link_to("View Details", course_path(course_date.course), :class => "ui inverted button")%>
                    </div>
                  </div>
                </div>
              </div>
              <%= link_to (image_tag course_date.course.avatar_url(:medium), :style => "width:100%; vertical-align: top;"), course_path(course_date.course) %>
            </div>
            <div class="content">
              <%= link_to(course_date.course.name, course_path(course_date.course), :class => "header text", :style => "color: white; font-size: 1em;") %>
            </div>
            <div class="extra content">
              <span class="left floated like text" style="color: #cdc5ff;">
                <i class="calendar icon"></i>
                <%= course_date.start_date.strftime("%d, %b, %Y") %>
              </span>
            </div>
        </div>
    <% end %>
</div>

app/views/course_dates/new.html.erb
<div class="course-form" style="width: 80%; margin:auto">
	<div class="ui segment" style="display:block">
	  <div class="column twelve wide">
			<div class="ui form time-select" style="max-width: 100%; margin: auto;">
				<%= form_for [@course, @course_date], :multipart => true do |form| %>
					<div class="four fields">
				  	<h3>Date & time</h3>
				  	<div class="field four wide">
				  		<%= form.text_field :start_date, :placeholder => "11/02/2015"%>
				  	</div>
				  	<div class="field four wide">
				  		<%= form.time_select :start_time, :class => "time-select" %>
				  	</div>
				  	<div class="field four wide">
				  		<%= form.text_field :end_date, :placeholder => "11/02/2015" %>
				  	</div>
				  	<div class="field four wide">
				  		<%= form.time_select :end_time %>
				  	</div>
				  </div>
			  	<%= form.fields_for :tickets do |builder| %>
				  	<% render 'ticket_fields_new', form: builder %>
			  	<% end %>
			  	<div class="ui segment no-box-shadow" style="margin-top: 40px;">
						<div class="ui dimmer courseLoader">
	            <div class="ui indeterminate text loader">Creating Course Date</div>
	          </div>
						<%= form.submit :id => "courseSubmit", :style =>"float:right; width:250px", :class => "ui inverted green button" %>
						<div class="ui error message" style="margin-top:50px;"></div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>